# Generated by Django 4.0.3 on 2023-05-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_menu_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='serial_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Serial number'),
        ),
    ]
