# Generated by Django 4.0.3 on 2023-05-01 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_menu_serial_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='serial_number',
        ),
    ]
