# Generated by Django 4.0.3 on 2023-05-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_menu_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='level',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Level'),
        ),
    ]
